### PR TITLE
kim-property module v2.3.0

### PR DESCRIPTION
**Pull request by yafshar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by yafshar** [comment]
@beckermr, thanks for your prompt reply. I forked the repo and made a pull request, which passed all the checks. After I merged this PR the same error is happening again.

**Comment by beckermr** [comment]
happy to help. Please follow the checklist. You missed another item.

>  Re-rendered with the latest conda-smithy (Use the phrase @conda-forge-admin, please rerender in a comment in this PR for automated rerendering)

**Comment by yafshar** [comment]
I do not understand where I should add `@conda-forge-admin, please rerender`

**Comment by yafshar** [comment]
@conda-forge-admin, please rerender¶

**Comment by yafshar** [comment]
@beckermr, can you help to fix this?

**Comment by yafshar** [comment]
OK, I did a new PR with `@conda-forge-admin, please rerender` in the comment.

**Pull request merged**
